import { Inter } from "next/font/google";
import "./components/App.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Data Entry Form",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
